services:
  - type: web
    name: opreport
    runtime: python
    pythonVersion: 3.11.11
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars: []
    databases:
      - name: section_cases
        databaseName: section_cases
        user: section_user
        plan: free
